<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('hris_departments')->insert([
            // [
            //     'name' => 'Human Resource Department',
            //     'description' => 'Human Resource Department',
            //     'is_active' => 1,
            //     'code' => 'HRD',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Management Information System',
            //     'description' => 'Management Information System',
            //     'is_active' => 1,
            //     'code' => 'MIS',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Car Carrier',
            //     'description' => 'Car Carrier',
            //     'is_active' => 1,
            //     'code' => 'CCO',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Finance Department',
            //     'description' => 'Finance Department',
            //     'is_active' => 1,
            //     'code' => 'FD',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Warehouse Department',
            //     'description' => 'Warehouse Department',
            //     'is_active' => 1,
            //     'code' => 'WD',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Maintenance Department',
            //     'description' => 'Maintenance Department',
            //     'is_active' => 1,
            //     'code' => 'MD',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Inter-Island',
            //     'description' => 'Inter-Island',
            //     'is_active' => 1,
            //     'code' => 'IID',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Marketing',
            //     'description' => 'Marketing',
            //     'is_active' => 1,
            //     'code' => 'MD',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Purchasing Department',
            //     'description' => 'Purchasing Department',
            //     'is_active' => 1,
            //     'code' => 'PD',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => '8MDL',
            //     'description' => '8MDL',
            //     'is_active' => 1,
            //     'code' => '8MDL',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => '3JUPITER',
            //     'description' => '3JUPITER',
            //     'is_active' => 1,
            //     'code' => '3JUPITER',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'CARGO',
            //     'description' => 'CARGO',
            //     'is_active' => 1,
            //     'code' => 'CARGO',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Office of the President',
            //     'description' => 'Office of the President',
            //     'is_active' => 1,
            //     'code' => 'OOP',
            //     'is_deleted' => null,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name' => 'Safety Department',
                'description' => 'Safety Department',
                'is_active' => 1,
                'code' => 'OOP',
                'is_deleted' => null,
                'deleted_by' => null,
                'deleted_at' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
