<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HrisPositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('hris_positions')->insert([
            // [
            //     'name' => 'Document Staff',
            //     'description' => 'Document Staff.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Dispatcher',
            //     'description' => 'Dispatcher.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Planner',
            //     'description' => 'Planner.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Shipment Coordinator',
            //     'description' => 'Shipment Coordinator.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Inventory Analyst',
            //     'description' => 'Inventory Analyst.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Gen. Account Team Leader',
            //     'description' => 'Gen. Account Team Leader',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Finance Manager',
            //     'description' => 'Finance Manager',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Courier Staff',
            //     'description' => 'Courier Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Accounting Associate',
            //     'description' => 'Accounting Associate',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Accounting Assistant Manager',
            //     'description' => 'Accounting Assistant Manager.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Accounting Manager',
            //     'description' => 'Accounting Manager.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Accounting Staff',
            //     'description' => 'Accounting Staff.',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Accounting Supervisor',
            //     'description' => 'Accounting Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Admin Staff',
            //     'description' => 'Admin Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Assistant Manager',
            //     'description' => 'Assistant Manager',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Apprentice',
            //     'description' => 'Apprentice',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Assistant Safety Officer',
            //     'description' => 'Assistant Safety Officer',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Aircon Technician',
            //     'description' => 'Aircon Technician',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Auditor',
            //     'description' => 'Auditor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Cash Custodian',
            //     'description' => 'Cash Custodian',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Billing Staff',
            //     'description' => 'Billing Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Billing & Payroll Supervisor',
            //     'description' => 'Billing & Payroll Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Billing & Payroll Staff',
            //     'description' => 'Billing & Payroll Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Company Nurse',
            //     'description' => 'Company Nurse',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Encoder',
            //     'description' => 'Encoder',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Supervisor',
            //     'description' => 'Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Fuel Tender',
            //     'description' => 'Fuel Tender',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'HR Officer',
            //     'description' => 'HR Officer',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'HRSS Manager',
            //     'description' => 'HRSS Manager',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'HR Staff',
            //     'description' => 'HR Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'HR Supervisor',
            //     'description' => 'HR Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Asst. Operation Manager',
            //     'description' => 'Asst. Operation Manager',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Inventory Staff',
            //     'description' => 'Inventory Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'IT Specialist',
            //     'description' => 'IT Specialist',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'IT Staff',
            //     'description' => 'IT Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Junior IT Supervisor',
            //     'description' => 'Junior IT Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'JR Supervisor Trainee',
            //     'description' => 'JR Supervisor Trainee',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'JR Supervisor',
            //     'description' => 'JR Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'MIS Head',
            //     'description' => 'MIS Head',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'MIS Supervisor',
            //     'description' => 'MIS Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Programmer',
            //     'description' => 'Programmer',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Marketing Officer',
            //     'description' => 'Marketing Officer',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            // [
            //     'name' => 'Marketing Head',
            //     'description' => 'Marketing Head',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Marketing and Sales Executive',
            //     'description' => 'Marketing and Sales Executive',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Marketing Associate',
            //     'description' => 'Marketing Associate',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Management Trainee',
            //     'description' => 'Management Trainee',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Maintenance Inspector',
            //     'description' => 'Maintenance Inspector',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Maintenance Supervisor',
            //     'description' => 'Maintenance Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Operation Manager',
            //     'description' => 'Operation Manager',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Operation Supervisor',
            //     'description' => 'Operation Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Purchasing Head',
            //     'description' => 'Purchasing Head',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Parts Control Leadman',
            //     'description' => 'Parts Control Leadman',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Parts Control Staff',
            //     'description' => 'Parts Control Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Expediter',
            //     'description' => 'Expediter',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Warehouse Staff',
            //     'description' => 'Warehouse Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Purchasing Staff',
            //     'description' => 'Purchasing Staff',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Pre-Delivery Inspector',
            //     'description' => 'Pre-Delivery Inspector',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'President',
            //     'description' => 'President',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Safety Officer',
            //     'description' => 'Safety Officer',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Quality Assesor',
            //     'description' => 'Quality Assesor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Revolving Fund Custodian',
            //     'description' => 'Revolving Fund Custodian',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Executive Secretary',
            //     'description' => 'Executive Secretary',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            // [
            //     'name' => 'Port Coordinator',
            //     'description' => 'Port Coordinator',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            // [
            //     'name' => 'Junior Supervisor',
            //     'description' => 'Junior Supervisor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Process Improvement Engineer',
            //     'description' => 'Process Improvement Engineer',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Team Leader - Safety & Quality',
            //     'description' => 'Team Leader - Safety & Quality',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Coordinator',
            //     'description' => 'Coordinator',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Checker',
            //     'description' => 'Checker',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Gate Pass Processor',
            //     'description' => 'Gate Pass Processor',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Truck Inspector',
            //     'description' => 'Truck Inspector',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Team Leader - Planning & Delivery',
            //     'description' => 'Team Leader - Planning & Delivery',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Planner - Port Transfer',
            //     'description' => 'Planner - Port Transfer',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Resource & Maintenance Coordinator',
            //     'description' => 'Resource & Maintenance Coordinator',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Asst. Job Controller',
            //     'description' => 'Asst. Job Controller',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Job Controller',
            //     'description' => 'Job Controller',
            //     'is_active' => 1,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name' => 'Helper Mechanic',
                'description' => 'Helper Mechanic',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mechanic',
                'description' => 'Mechanic',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Project Design Engr.',
                'description' => 'Project Design Engr.',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
