<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ims_items')->insert([
            // [
            //     'item_brand_id' => 3,
            //     'item_type_id' => 5,
            //     'description' => 'MSI Monitor',
            //     'price' => 3620,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 6,
            //     'item_type_id' => 4,
            //     'description' => 'Mouse',
            //     'price' => 225,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 6,
            //     'item_type_id' => 6,
            //     'description' => 'Logi Speaker',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 6,
            //     'item_type_id' => 3,
            //     'description' => 'Logitech Keyboard',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 8,
            //     'item_type_id' => 3,
            //     'description' => 'A4Tech Keyboard',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 8,
            //     'item_type_id' => 7,
            //     'description' => 'A4Tech Webcam',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 12,
            //     'item_type_id' => 6,
            //     'description' => 'Generic Speaker',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 12,
            //     'item_type_id' => 3,
            //     'description' => 'Generic Keyboard',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 12,
            //     'item_type_id' => 3,
            //     'description' => 'Generic Keyboard',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'item_brand_id' => 12,
            //     'item_type_id' => 7,
            //     'description' => 'Generic Webcam',
            //     'price' => 678,
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'item_brand_id' => 27,
                'item_type_id' => 22,
                'description' => 'Hyperx Fury 8GB Ram',
                'price' => 678,
                'is_active' => 1,
                'is_deleted' => 0,
                'deleted_by' => null,
                'deleted_at' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
