<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ims_item_brands')->insert([
            // [
            //     'name' => 'Lenovo',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'AOC',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'MSI',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'HP',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Philips',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Logtech',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Epson',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'A4Tech',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Samsung',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Secure',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'TP Link',
            //     'description' => '',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Generic',
            //     'description' => 'No Brand',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Hyperx Fury',
            //     'description' => 'Hyperx Fury',
            //     'is_active' => 1,
            //     'is_deleted' => 0,
            //     'deleted_by' => null,
            //     'deleted_at' => null,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

        ]);
    }
}
